project_name: yamlcanonizer
builds:
  - dir: cmd/yamlcanonizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -extldflags "-static"
      - -s
      - -w
      - -X "main.version=v{{ .Version }}"
archives:
  - format: tar.gz
    wrap_in_directory: "false"
    replacements:
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
brews:
  - tap:
      owner: nestoca
      name: homebrew-yamlcanonizer
    homepage: "https://github.com/nestoca/yamlcanonizer"
    description: >-
      Canonizes a set of yaml documents into a standardized and sorted form that is suitable for comparison against another set
    license: "MIT"
